// Copy KaTeX CSS + woff2 fonts from node_modules to site/public/_katex/ so
// the stylesheet and its fonts are served self-hosted (ADR-0012 CSP:
// `font-src 'self'`, no CDN). Runs as `prebuild` — Astro copies `public/`
// verbatim to the built site, so `/_katex/katex.min.css` and
// `/_katex/fonts/…` resolve at runtime with no bundler in the loop.
//
// Only woff2 is copied: revkit's browser matrix is evergreen (ADR-0018), and
// woff2 is the only font format modern browsers need — pulling in ttf and
// woff siblings would triple the shipped font weight for no supported UA.
import { existsSync, mkdirSync, readdirSync, rmSync, statSync } from "node:fs";
import { copyFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const require_ = createRequire(import.meta.url);

/** Locate the katex `dist/` directory via require.resolve so bun / node /
 * a hoisted workspace install all agree on where katex lives. */
function katexDistDir(): string {
  const packageJson = require_.resolve("katex/package.json");
  return join(dirname(packageJson), "dist");
}

function ensureCleanDir(dir: string): void {
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
}

function copyWoff2Fonts(srcFontsDir: string, destFontsDir: string): number {
  let copied = 0;
  for (const entry of readdirSync(srcFontsDir)) {
    if (!entry.endsWith(".woff2")) continue;
    const srcFile = join(srcFontsDir, entry);
    if (!statSync(srcFile).isFile()) continue;
    copyFileSync(srcFile, join(destFontsDir, entry));
    copied += 1;
  }
  return copied;
}

const siteRoot = join(dirname(new URL(import.meta.url).pathname), "..");
const outDir = join(siteRoot, "public", "_katex");
const outFontsDir = join(outDir, "fonts");

const distDir = katexDistDir();
const srcCss = join(distDir, "katex.min.css");
const srcFonts = join(distDir, "fonts");

if (!existsSync(srcCss) || !existsSync(srcFonts)) {
  throw new Error(
    `copy-katex-assets: expected katex.min.css and fonts/ under ${distDir}; ` +
      `got css=${existsSync(srcCss)}, fonts=${existsSync(srcFonts)}`,
  );
}

ensureCleanDir(outDir);
mkdirSync(outFontsDir, { recursive: true });
copyFileSync(srcCss, join(outDir, "katex.min.css"));
const copied = copyWoff2Fonts(srcFonts, outFontsDir);

if (copied === 0) {
  throw new Error(
    `copy-katex-assets: no *.woff2 files copied from ${srcFonts}; the KaTeX install is missing woff2 fonts`,
  );
}

const katexPackage = require_("katex/package.json") as { version: string };
// A small stamp so a reader tracing `_katex/` finds the source. Astro copies
// public verbatim into the build, so this ends up served from the site as
// plain text — keeping the CSP surface unchanged.
writeFileSync(
  join(outDir, "README.txt"),
  `Generated by site/scripts/copy-katex-assets.ts from katex@${katexPackage.version}. Do not edit by hand.\n`,
);

// Build-script progress log surfaces in `just build` output so the reader
// can see the KaTeX assets landed and their count.
console.log( // guardrails-ok(no-debug-leftovers): CLI progress output
  `copy-katex-assets: wrote katex.min.css + ${copied} woff2 fonts to ${outDir} (katex@${katexPackage.version})`,
);
