import { readFileSync, writeFileSync } from "node:fs";

// This account is the owner's explicit dev boundary (#160), never a production default.
export const DEV_ACCOUNT = "1ecb6c28f07ad10630be568fcf73a347";
export const DEV_WORKER = "revkit-review-dev";
export const DEV_BUCKET = "revkit-previews-dev";
export interface DevState {
  account_id: string;
  worker_name: string;
  d1: { database_name: string; database_id: string };
  r2: { previews_bucket: string };
}
interface WranglerConfig {
  name: string;
  account_id?: string;
  workers_dev: boolean;
  compatibility_flags: string[];
  d1_databases: { binding: string; database_name: string; database_id: string }[];
  r2_buckets: { binding: string; bucket_name: string }[];
  [key: string]: unknown;
}
export function readBaseConfig(path: string): WranglerConfig {
  // The tracked file uses full-line comments only; JSON.parse rejects unsupported JSONC.
  const config = JSON.parse(readFileSync(path, "utf8").replace(/^\s*\/\/.*$/gm, "")) as WranglerConfig;
  if (config.workers_dev !== false || "route" in config || "routes" in config ||
      !Array.isArray(config.compatibility_flags) || config.compatibility_flags.length !== 0 ||
      "account_id" in config || "env" in config || "custom_domains" in config) {
    throw new Error("cf-dev: inherited security settings require workers_dev:false, no routes/account/env and empty compatibility_flags");
  }
  if (config.d1_databases?.length !== 1 || config.d1_databases[0]?.binding !== "DB" ||
      config.r2_buckets?.length !== 1 || config.r2_buckets[0]?.binding !== "PREVIEWS") {
    throw new Error("cf-dev: expected one DB and one PREVIEWS binding");
  }
  return config;
}
export function validateDevState(state: DevState): void {
  if (state.account_id !== DEV_ACCOUNT || state.worker_name !== DEV_WORKER ||
      state.d1?.database_name !== DEV_WORKER || state.r2?.previews_bucket !== DEV_BUCKET ||
      !/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(state.d1?.database_id ?? "")) {
    throw new Error("cf-dev: state must identify the authorized dev account and resources with a valid D1 UUID");
  }
}
export function generateDevConfig(base: WranglerConfig, state: DevState, path: string): void {
  validateDevState(state);
  const config = structuredClone(base);
  config.name = state.worker_name;
  config.account_id = state.account_id;
  Object.assign(config.d1_databases[0]!, state.d1);
  config.r2_buckets[0]!.bucket_name = state.r2.previews_bucket;
  writeFileSync(path, "// GENERATED by just cf-dev. Local dev identifiers; do not commit.\n" + JSON.stringify(config, null, 2) + "\n");
}
