// The ONE client asset the hosted Worker serves: where it lives, what it is
// called, how its name is derived from its bytes, and which paths answer.
//
// M4 slice 5b. `src/index.ts`'s `revkit-bundle` case used to be a 404 for every
// path, while `script-src` allowlisted `/_revkit/<version>/` — a policy naming a
// path that served nothing. This module is what makes that path real, and the
// rest of the slice is what makes naming it safe.
//
// ── The naming scheme, and why content-addressing rather than a version alone ─
//
//     /_revkit/<revkit-version>/invite-<sha256-of-these-bytes>.js
//
// Three parts, each load-bearing:
//
//   - **The version segment** is `env.REVKIT_VERSION`, so it is the version the
//     Worker RUNS and nothing else. ADR-0012 requires `script-src` to name only
//     the current version "so a page can't load an older, possibly vulnerable
//     bundle", and this is the half of that the route can enforce: a path
//     naming any other version is a 404, so an old bundle is not merely
//     unlisted, it is unreachable.
//   - **The file stem** is a constant, so there is exactly one asset and no
//     directory listing to reason about.
//   - **The digest** is SHA-256 over the exact bytes this module serves, in
//     full — all 64 hex characters, not a truncated prefix. Truncation is the
//     usual practice and it is defensible, but the full digest makes "the name
//     IS the content address" exactly true rather than nearly true, which in
//     turn makes one claim in the next section checkable instead of argued.
//
// ── The digest is computed FROM the served string, so it cannot drift ──────
//
// There is no committed hash to fall out of step with the source: the same
// `INVITE_CLIENT_SCRIPT` constant is what gets digested and what gets written to
// the response body, in the same request. A build that changed nothing produces
// the same name, so the name is a stable cache key; a build that changed
// anything produces a different one.
//
// ── How a STALE asset is handled, which is the interesting case ────────────
//
// There is no staleness window, and that is a property of the scheme rather
// than a policy someone has to remember:
//
//   - An OLD VERSION's path 404s, always. There is no window in which yesterday's
//     bundle is still fetchable.
//   - A NEW build's name is a name the old HTML never referenced, because the
//     HTML is generated by the same Worker that serves the asset — a page and
//     its script can never disagree, because they come from the same digest.
//   - A page already OPEN in a browser when the Worker is redeployed keeps
//     asking for the old digest, which now 404s, and the page's form still
//     works (the token is in the hidden field). That is a real, accepted
//     consequence: an open tab loses its script, and with it the token
//     stripping, for as long as it stays open. It is recorded rather than
//     engineered away, because the alternative — serving an old digest from a
//     new Worker — is precisely the "load an older, possibly vulnerable
//     bundle" that ADR-0012 forbids.
//
// Serving the OLD bytes under the NEW version's path was rejected for the same
// reason: it would make the name a lie, and the name is the cache key.
//
// ── Every other spelling is a 404, and never a redirect ────────────────────
//
// Matching is exact string equality against the one name that resolves, so
// there is no pattern to widen and no directory to traverse: an unhashed name, a
// mis-hashed name, a `.mjs` spelling, the version as a directory, and the bare
// `/_revkit/` all miss. In particular:
//
//   - **No unhashed alias.** A stable URL is what browsers and every
//     intermediary cache key on, so an unhashed name would make the digest
//     decorative.
//   - **No redirect, ever.** ADR-0012: browsers drop the path part of a CSP
//     source after a redirect, so a redirect under `/_revkit/` would silently
//     widen `script-src` from one pinned directory to whatever the `Location`
//     names. `revkitBundlePath` already refuses to construct a redirecting
//     version alias, and this module adds no second way to produce one.

import { revkitBundlePath } from "./headers.ts";
import { INVITE_CLIENT_SCRIPT } from "./client-script.ts";

/** The asset's file stem. One asset, so a constant, and no directory listing
 * exists to reason about. */
const CLIENT_ASSET_STEM = "invite";

/** The asset's filename without its digest — the spelling with the digest
 * REMOVED, which is a 404 like any other. Named because a test needs to write
 * that refused spelling, and deriving it here keeps it from being assembled by
 * hand somewhere. */
export const CLIENT_ASSET_FILE = `${CLIENT_ASSET_STEM}.js`;

/**
 * The asset's media type, and the only one it is ever served with.
 *
 * **A constant, not something derived from the request.** ADR-0012 says the
 * Worker derives `Content-Type` "from the file extension against its own
 * allowlist, never from artifact or object metadata". There is exactly one
 * extension in the allowlist and exactly one asset, so the extension match is a
 * constant rather than a lookup — and a request cannot reach a spelling whose
 * extension is not this one, because only the exact name resolves.
 *
 * `X-Content-Type-Options: nosniff` (attached by the shared policy for every
 * response) is what makes this load-bearing: without it a browser may treat a
 * mislabelled response as HTML and execute it in this origin.
 */
export const CLIENT_ASSET_MEDIA_TYPE = "text/javascript; charset=utf-8";

/**
 * `immutable`, and the scheme is what makes it true rather than optimistic.
 *
 * A name that resolves always resolves to these bytes for this version, and
 * every other name is a 404 — so there is nothing a revalidation could ever
 * return differently. `public` is safe for the same reason: the bytes are the
 * same for every caller and contain nothing about any of them.
 *
 * **The HTML pages are `no-store` and this is not** (`src/index.ts`'s `html`).
 * The pages carry an invite token and a browser binding; this carries a constant
 * that is compiled into the Worker.
 */
export const CLIENT_ASSET_CACHE_CONTROL = "public, max-age=31536000, immutable";

/** The bytes this asset serves — the source, exactly, with nothing appended. */
export function clientAssetSource(): string {
  return INVITE_CLIENT_SCRIPT;
}

/** The SHA-256 of `clientAssetSource()`, as lowercase hex.
 *
 * **WebCrypto, not a hash from `@revkit/review-core`.** `compatibility_flags` is
 * `[]`, so the Worker has no `Buffer` and no `node:crypto`; `crypto.subtle` is
 * the platform's, and `hexToBase64` in the shared header policy is the precedent
 * for hand-rolling the small conversion this needs rather than importing a
 * Node-flavoured one.
 *
 * **Memoised per isolate.** It is a digest of a compile-time constant, so it is
 * the same answer for the life of the isolate, and it is computed once per
 * Worker instance rather than once per request. The promise is cached rather
 * than the resolved string so two concurrent first-requests share one digest.
 */
let digestPromise: Promise<string> | undefined;

export function clientAssetDigest(): Promise<string> {
  digestPromise ??= crypto.subtle
    .digest("SHA-256", new TextEncoder().encode(clientAssetSource()))
    .then((bytes) => [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, "0")).join(""));
  return digestPromise;
}

/**
 * The one path that resolves: `/_revkit/<version>/invite-<digest>.js`.
 *
 * Built on `revkitBundlePath`, so the version segment is validated by the same
 * function that builds `script-src` — a version that would widen the policy
 * cannot reach here either.
 */
export function clientAssetPath(version: string, digest: string): string {
  return `${revkitBundlePath(version)}${CLIENT_ASSET_STEM}-${digest}.js`;
}

/**
 * The `<script src>` a page for THIS version carries — the one URL that resolves.
 *
 * **Memoised per version, and in this module rather than in `src/index.ts`,**
 * because two things need the URL and must not be able to disagree: the page
 * that names it and the route that answers it. Both call this, so there is no
 * second derivation of the string to drift from `clientAssetPath`.
 */
const scriptSrcCache = new Map<string, Promise<string>>();

export function clientScriptSrc(version: string): Promise<string> {
  const cached = scriptSrcCache.get(version);
  if (cached !== undefined) return cached;
  const pending = clientAssetDigest().then((digest) => clientAssetPath(version, digest));
  scriptSrcCache.set(version, pending);
  return pending;
}

/**
 * Does this pathname name exactly this version's asset?
 *
 * **Exact equality, deliberately — not a pattern, not a prefix.** A pattern is
 * something a future edit can widen; equality has nothing to widen. Everything
 * that is not the one name is a 404, which is what makes "an old bundle is
 * unreachable", "there is no unhashed alias" and "`/_revkit/` never redirects"
 * three consequences of one comparison instead of three rules.
 */
export function isClientAssetPath(pathname: string, version: string, digest: string): boolean {
  return pathname === clientAssetPath(version, digest);
}
